name: 'Setup test environment'
description: 'Setup the basic test environment for a CI run'
inputs:
  primary_repository:
    description: "The repository to checkout, in the form shakenfist/shakenfist"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "SF_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        echo "SF_PRIMARY_REPO=$( echo ${{ github.repository }} | cut -f 2 -d '/' )" >> $GITHUB_ENV
        echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

    - name: Checkout the actions repository
      uses: actions/checkout@v4
      with:
        repository: shakenfist/actions
        path: actions
        fetch-depth: 0

    # NOTE(mikal): clone_with_depends doesn't work with merge queues because
    # when we hit the queue we no longer have the branch that is our PR to use
    # to map to the other repos. So instead we're just going to have to land
    # things in the right order and get on with our lives.
    - name: Checkout shakenfist
      uses: actions/checkout@v4
      with:
        repository: shakenfist/shakenfist
        path: shakenfist
        fetch-depth: 0

    - name: Checkout client-python
      uses: actions/checkout@v4
      with:
        repository: shakenfist/client-python
        path: client-python
        fetch-depth: 0

    - name: Checkout agent-python
      uses: actions/checkout@v4
      with:
        repository: shakenfist/agent-python
        path: agent-python
        fetch-depth: 0