- hosts: localhost
  gather_facts: yes
  connection: ssh
  vars:
    base: rocky:9
    identifier: unknown
    sshkey: '/srv/github/id_ci.pub'
    environment_name: kolla

  tasks:
    - name: Create a network
      sf_network:
        netblock: "10.0.2.0/24"
        name: "{{environment_name}}"
        namespace: "{{identifier}}"
        state: present
        dns: true
      register: environment_network

    - name: Log environment network
      debug:
        msg:
          - "New network: {{ environment_network }}"

    - include_tasks: kerbside-create-instance.yml
      vars:
        - name: "deploy"
        - address: "10.0.2.2"
        - vcpus: 2
        - memory: 2048
        - base: "{{ base }}"
        - tag: "{{environment_name}}-mid"

    - include_tasks: kerbside-create-instance.yml
      vars:
        - name: "control-1"
        - address: "10.0.2.10"
        - vcpus: 6
        - memory: 16384
        - base: "{{ base }}"
        - tag: "{{environment_name}}-high"

    - include_tasks: kerbside-create-instance.yml
      vars:
        - name: "control-2"
        - address: "10.0.2.11"
        - vcpus: 6
        - memory: 16384
        - base: "{{ base }}"
        - tag: "{{environment_name}}-high"

    - include_tasks: kerbside-create-instance.yml
      vars:
        - name: "compute-1"
        - address: "10.0.2.20"
        - vcpus: 6
        - memory: 16384
        - base: "{{ base }}"
        - tag: "{{environment_name}}-low"

    - include_tasks: kerbside-create-instance.yml
      vars:
        - name: "kerbside-1"
        - address: "10.0.2.30"
        - vcpus: 2
        - memory: 2048
        - base: "{{ base }}"
        - tag: "{{environment_name}}-high"

    - include_tasks: kerbside-create-instance.yml
      vars:
        - name: "kerbside-2"
        - address: "10.0.2.31"
        - vcpus: 2
        - memory: 2048
        - base: "{{ base }}"
        - tag: "{{environment_name}}-high"

    - name: Additional tasks for CI
      tags: ci
      block:
      - name: Add environment network interface to primary instance
        shell: |
          sf-client instance add-interface -n "{{environment_name}}" "{{identifier}}"
          sleep 30

      - name: Determine the interface name for the new interface
        shell: |
          ip a | egrep "^[0-9]+: ens" | cut -f 2 -d " " | sed 's/:.*//'
        register: primary_new_interface
        retries: 6
        delay: 30
        until: primary_new_interface.stdout != ""

      - debug:
          msg:
            - "New interface on primary: {{ primary_new_interface.stdout }}"

      - name: DHCP on new interface
        become: true
        shell: "dhclient {{ primary_new_interface.stdout }}"

      - name: Collect address details for new interface
        shell: "ip -4 addr show {{ primary_new_interface.stdout }} | grep inet | sed -e 's/.*inet //' -e 's|/.*||'"
        register: primary_new_address

      - debug:
          msg:
            - "New interface address: {{ primary_new_address.stdout }}"

      - name: Write details of instances to workspace
        copy:
          content: |
            {% for svr in groups.sfall %}
            export {{ svr | replace('-', '_') }}={{hostvars[svr]['ansible_ssh_host']}}
            export {{ svr | replace('-', '_') }}_uuid={{hostvars[svr]['sf_uuid']}}
            {% endfor %}

            export identifier={{identifier}}
            export nodes="{{ groups.sfall | join(' ') | replace('-', '_') }}"
            export ENVIRONMENT="{{ primary_new_address.stdout }}"
          dest: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/ci-environment.sh"
          owner: debian
          group: debian
          mode: u=r,g=r,o=r

      - name: Log environment details path
        debug:
          msg: "Environment details written to {{ lookup('env', 'GITHUB_WORKSPACE') }}/ci-environment.sh"

    - name: Wait for all instances to present an "OpenSSH" prompt
      wait_for:
        port: 22
        host: "{{hostvars[item]['ansible_ssh_host']}}"
        search_regex: OpenSSH
        delay: 60
        timeout: 300
      with_items: "{{ groups['sfall'] }}"
