#!/bin/bash

cd shakenfist

datestamp=$(date "+%Y%m%d")
git checkout develop
git pull
git checkout -b sync-docs
git rebase develop

# Path to the sync script (in the actions repository)
SYNC_SCRIPT="${GITHUB_WORKSPACE}/actions/tools/sync_component_docs.py"

# Sync kerbside docs
KERBSIDE=$(python3 "${SYNC_SCRIPT}" kerbside \
    "${GITHUB_WORKSPACE}/kerbside/docs" \
    "${GITHUB_WORKSPACE}/shakenfist/docs/components/kerbside")
git add docs/components/kerbside

# Add additional component syncs here, for example:
# CLINGWRAP=$(python3 "${SYNC_SCRIPT}" clingwrap \
#     "${GITHUB_WORKSPACE}/clingwrap/docs" \
#     "${GITHUB_WORKSPACE}/shakenfist/docs/components/clingwrap")
# git add docs/components/clingwrap

# Regenerate mkdocs.yml from template
# The template should contain placeholders like %%kerbside%% that get replaced
# with the navigation snippets generated by the sync script
sed "s/%%kerbside%%/${KERBSIDE}/" mkdocs.yml.tmpl > mkdocs.yml

# Did we find something new?
if [ $(git diff | wc -l) -gt 0 ]; then
    echo "Change detected..."
    echo
    git diff

    git config --global user.name "shakenfist-bot"
    git config --global user.email "bot@shakenfist.com"
    git commit -a -m "Automated documentation sync for ${datestamp}."
    git push -f origin sync-docs
    echo
    gh pr create \
        --assignee mikalstill \
        --reviewer mikalstill \
        --title "Automated documentation sync for ${datestamp}." \
        --body "Automated documentation sync."
    echo
    echo "Pull request created."
fi